# fly.toml app configuration file generated for sqlemail on 2023-08-05T00:55:12+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "sqlemail"
primary_region = "cdg"

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[services]]
  internal_port = 25
  protocol = "tcp"
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  [[services.ports]]
    port = 25

[mounts]
  source = "litefs"
  destination = "/var/lib/litefs"
